### ISSUE TITLE
Port map name alias support

### ISSUE THREAD

**Issue by webdev778** [interscript/lcs#8]
moct-kor-Hang-Latn-2000.yaml has this part

```
alias:
  ogc11122:
    code: kor_Hang2Latn_MOCT_2000
    description: Korean Ministry of Culture and Tourism 2000 System
```

Find the best way to support aliases in the new codebase
